[package]
name = "elentium/random"
version = "2.1.0"
license = "MIT"
authors = ["IAMNOTULTRA3"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["roblox-studio-insert"]
